# Configuration for pullapprove.com
#
# Approval access and primary role is determined by info in the project ownership spreadsheet:
# https://docs.google.com/spreadsheets/d/1-HIlzfbPYGsPr9KuYMe6bLfc4LXzPjpoALqtYRYTZB0/edit?pli=1#gid=0&vpid=A5
#
# === GitHub username to Full name map ===
#
# alexeagle - Alex Eagle
# alxhub - Alex Rickabaugh
# brocco - Mike Brocchi
# chuckjaz - Chuck Jazdzewski
# filipesilva - Filipe Silva
# gkalpak - George Kalpakas
# hansl - Hans Larsen
# IgorMinar - Igor Minar
# jasonaden - Jason Aden
# kapunahelewong - Kapunahele Wong
# kara - Kara Erickson
# matsko - Matias Niemelä
# mhevery - Misko Hevery
# petebacondarwin - Pete Bacon Darwin
# pkozlowski-opensource - Pawel Kozlowski
# robwormald - Rob Wormald
# tinayuangao - Tina Gao
# vicb - Victor Berchet
# vikerman - Vikram Subramanian


version: 2

group_defaults:
  required: 1
  reset_on_reopened:
    enabled: true
  approve_by_comment:
    enabled: false
  # see http://docs.pullapprove.com/groups/author_approval/
  author_approval:
    # If the author is a reviewer on the PR, they will automatically have an "approved" status.
    auto: true

groups:
  # Require all PRs to have at least one approval from *someone*
  all:
    users: all
    required: 1
    rejection_value: -999
    # In this group, your self-approval does not count
    author_approval:
      auto: false
      ignored: true
    files:
      include:
        - "*"

  root:
    conditions:
      files:
        include:
          - "*"
        exclude:
          - "WORKSPACE"
          - "BUILD.bazel"
          - ".circleci/*"
          - "aio/*"
          - "integration/*"
          - "modules/*"
          - "packages/*"
          - "tools/*"
    users:
      - IgorMinar
      - mhevery

  public-api:
    conditions:
      files:
        include:
          - "tools/public_api_guard/*"
    users:
      - IgorMinar
      - mhevery

  bazel:
    conditions:
      files:
        include:
          - "WORKSPACE"
          - "*.bazel"
          - "*.bzl"
          - "packages/bazel/*"
          - "tools/bazel.rc"
    users:
      - alexeagle #primary
      - chuckjaz
      - IgorMinar #fallback
      - mhevery
      - vikerman #fallback

  build-and-ci:
    conditions:
      files:
        include:
          - "*.yml"
          - "*.json"
          - "*.lock"
          - "tools/*"
        exclude:
          - "tools/bazel.rc"
          - "tools/public_api_guard/*"
          - "aio/*"
    users:
      - IgorMinar #primary
      - alexeagle
      - jasonaden
      - mhevery #fallback

  integration:
    conditions:
      files:
        - "integration/*"
    users:
      - alexeagle
      - mhevery
      - vicb
      - IgorMinar #fallback

  core:
    conditions:
      files:
        - "packages/core/*"
    users:
      - mhevery #primary
      - chuckjaz
      - kara
      - vicb
      - IgorMinar #fallback

  animations:
    conditions:
      files:
        - "packages/animations/*"
        - "packages/platform-browser/animations/*"
    users:
      - matsko #primary
      - mhevery #fallback
      - IgorMinar #fallback

  compiler/i18n:
    conditions:
      files:
        - "packages/compiler/src/i18n/*"
    users:
      - vicb #primary
      - chuckjaz
      - IgorMinar #fallback
      - mhevery #fallback

  compiler:
    conditions:
      files:
        - "packages/compiler/*"
    users:
      - chuckjaz #primary
      - vicb
      - mhevery
      - IgorMinar #fallback

  compiler-cli/ngtools:
    conditions:
      files:
        - "packages/compiler-cli/src/ngtools*"
    users:
      - hansl
      - filipesilva #fallback
      - brocco #fallback
      - IgorMinar #fallback

  compiler-cli:
    conditions:
      files:
        include:
          - "packages/compiler-cli/*"
          - "packages/bazel/*"
        exclude:
          - "packages/compiler-cli/src/ngtools*"
    users:
      - alexeagle
      - chuckjaz
      - vicb
      - IgorMinar #fallback
      - mhevery #fallback

  common:
    conditions:
      files:
        include:
          - "packages/common/*"
        exclude:
          - "packages/common/http/*"
    users:
      - pkozlowski-opensource #primary
      - vicb
      - IgorMinar #fallback
      - mhevery #fallback

  forms:
    conditions:
      files:
        - "packages/forms/*"
        - "aio/content/guide/forms.md"
        - "aio/content/guide/form-validation.md"
        - "aio/content/guide/reactive-forms.md"
        - "aio/content/examples/forms/*"
        - "aio/content/examples/form-validation/*"
        - "aio/content/examples/reactive-forms/*"
    users:
      - kara #primary
      - tinayuangao #secondary
      - IgorMinar #fallback
      - mhevery #fallback

  http:
    conditions:
      files:
        - "packages/common/http/*"
        - "packages/http/*"
    users:
      - alxhub #primary
      - IgorMinar
      - mhevery #fallback

  language-service:
    conditions:
      files:
        - "packages/language-service/*"
    users:
      - chuckjaz #primary
      # needs secondary
      - vicb
      - IgorMinar #fallback
      - mhevery #fallback

  router:
    conditions:
      files:
        - "packages/router/*"
    users:
      - jasonaden #primary
      - vicb
      - IgorMinar #fallback
      - mhevery #fallback

  upgrade:
    conditions:
      files:
        - "packages/upgrade/*"
    users:
      - petebacondarwin #primary
      - gkalpak
      - IgorMinar #fallback
      - mhevery #fallback

  platform-browser:
    conditions:
      files:
        - "packages/platform-browser/*"
    users:
      - vicb #primary
      # needs secondary
      - IgorMinar #fallback
      - mhevery #fallback

  platform-server:
    conditions:
      files:
        - "packages/platform-server/*"
    users:
      - vikerman #primary
      - alxhub #secondary
      - vicb
      - IgorMinar #fallback
      - mhevery #fallback

  platform-webworker:
    conditions:
      files:
        - "packages/platform-webworker/*"
    users:
      - vicb #primary
      # needs secondary
      - IgorMinar #fallback
      - mhevery #fallback

  service-worker:
    conditions:
      files:
        - "packages/service-worker/*"
    users:
      - alxhub #primary
      - gkalpak
      - IgorMinar #fallback
      - mhevery #fallback

  benchpress:
    conditions:
      files:
        - "packages/benchpress/*"
    users:
      - alxhub # primary
      # needs secondary
      - IgorMinar #fallback
      - mhevery #fallback

  angular.io:
    conditions:
      files:
        include:
          - "aio/*"
        exclude:
          - "aio/content/*"
    users:
      - petebacondarwin #primary
      - IgorMinar
      - gkalpak
      - mhevery #fallback

  angular.io-guide-and-tutorial:
    conditions:
      files:
        include:
          - "aio/content/*"
        exclude:
          - "aio/content/marketing/*"
          - "aio/content/navigation.json"
          - "aio/content/license.md"
    users:
      - kapunahelewong
      - stephenfluin
      - petebacondarwin
      - gkalpak
      - IgorMinar
      - mhevery #fallback

  angular.io-marketing:
    conditions:
      files:
        include:
          - "aio/content/marketing/*"
          - "aio/content/navigation.json"
          - "aio/content/license.md"
    users:
      - stephenfluin
      - petebacondarwin
      - gkalpak
      - IgorMinar
      - mhevery #fallback
